name: get openstack kolla core images

on:
  schedule:
    - cron:  "0 0 * * 0"
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get kolla core images
        env:
          WXPUSHER_APPTOKEN: ${{ secrets.WXPUSHER_APPTOKEN }}
          WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}
        run: sudo -E bash get-kolla-core-images.sh
